"""Guard: a deliberately-deleted identifier must not survive in the spec tree as current API.

DEF167 and DEF171 are the same defect twice, two weeks apart, and `failure_patterns.md`
says the second occurrence gets a guard rather than a second fix:

  * CR117 vacated the name `FlatTopHexagonClipper` **on purpose**, so that any stale
    reference would be a compile error. The safety argument holds for Dart and holds
    nowhere else — `data_viz_and_meters.md` and `CR120.md` went on naming it as current
    API, and prose does not fail to compile. A builder who reads the spec first (which is
    what specs are for) copies a compile error out of it.
  * CR114 / DEF129 deleted `daily_briefing` and `DailyBriefing`. The deletion was safe at
    runtime because Pydantic's `extra='ignore'` loads old snapshots cleanly — verified —
    but nothing makes a *reader* fail, and five spec docs kept describing the field.

So the shape is: a deletion whose safety rests on every remaining reference being loud,
plus a class of reference that is silent. This test is the missing loudness.

WHY DEFAULT-DENY, AND WHY THE ESCAPE HATCH LOOKS LIKE THIS
----------------------------------------------------------
A vacated name legitimately appears in prose that *records the removal* — "REMOVED (CR114
/ DEF129)" is exactly what a good spec says, and banning the string outright would delete
the paper trail this project depends on. So a mention passes if it is **acknowledged as
dead** on its own line (see `_DEATH_MARKERS`), and otherwise fails.

That leaves a handful of lines that are genuinely historical but phrased without a marker.
Those go in `ACKNOWLEDGED`, keyed by (path, identifier), each with a reason. That list is
hand-maintained — which is the thing DEF191 criticises elsewhere — but the polarity is the
point: the **default is failure**. A new spec naming a dead identifier fails the build and
someone has to consciously either fix it or justify it. That is the opposite of the
hand-written checklist that passes vacuously when nobody remembers to extend it.

TO EXTEND: when a change deliberately vacates an identifier, add one `_Vacated` entry in
the same commit. That entry is what makes the next deletion cheap.

KNOWN LIMIT, stated rather than discovered later: the death-marker rule is per-line and
keyword-based, so a line that both prescribes the dead name *and* happens to contain one
of `_DEATH_MARKERS` passes — e.g. "use `FlatTopHexagonClipper`; the old chip was removed".
That is a real hole and it is the price of not banning the paper trail. It is narrower than
the defect it replaces (which caught nothing at all), and the failure mode is a false PASS
on an unusual sentence rather than a false FAIL on every removal record. If it ever fires
in practice, the fix is a window-based check around the match, not a longer keyword list.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DOCS = REPO_ROOT / "docs"


@dataclass(frozen=True)
class _Vacated:
    """An identifier a change deliberately removed, and where it may still be named."""

    identifier: str
    vacated_by: str
    replacement: str
    # Directories/files that are history by construction and never describe current API.
    exempt_paths: tuple[str, ...] = field(default=())


# Paths that are historical or generated by construction. A vacated name appearing here is
# a record, not a prescription — and two of them (the registers) are GENERATED from row
# files (CR081), so "fixing" them would be overwritten on the next regenerate anyway.
_GLOBAL_EXEMPT: tuple[str, ...] = (
    "docs/archive/",
    "docs/defect/_registry/",
    "docs/forward_planning/_registry/",
    "docs/defect/def_list.md",
    "docs/forward_planning/cr_list.md",
    "docs/governance/daily_cr_def_review_log.md",
    "original_silent_scout_research/",
)

# A line that says the thing is dead is doing its job. Matched case-insensitively against
# the whole line, so "REMOVED (CR114 …)" and "was deleted by" both qualify.
_DEATH_MARKERS: tuple[str, ...] = (
    "removed",
    "deleted",
    "no longer",
    "vacated",
    "gone",
    "dropped",
    "will not compile",
    "do not re-add",
    "do not cite",
)

VACATED: tuple[_Vacated, ...] = (
    _Vacated(
        identifier="FlatTopHexagonClipper",
        vacated_by="CR117",
        replacement=(
            "CutCornerOctagonClipper (8 sides, the default control shape), "
            "FlatTopHexagonBarClipper (6, angled ends, any aspect ratio), "
            "or FlatTopRegularHexagon (6, locked 2:sqrt(3))"
        ),
    ),
    _Vacated(
        identifier="DailyBriefing",
        vacated_by="CR114 / DEF129",
        replacement="nothing — the model was deleted, there is no successor",
    ),
    _Vacated(
        identifier="daily_briefing",
        vacated_by="CR114 / DEF129",
        replacement="nothing — the mandate field was deleted, there is no successor",
        exempt_paths=(
            # The defect folder that *is* the record of the deletion.
            "docs/defect/DEF129_concierge_claims_capabilities_that_do_not_exist/",
        ),
    ),
)

# (repo-relative path, identifier) -> why this mention is legitimate despite carrying no
# death marker on its own line. Default-deny's escape hatch: adding an entry is deliberate.
ACKNOWLEDGED: dict[tuple[str, str], str] = {
    (
        "docs/initial_specs/05_design/ami_hex_in_flutter.md",
        "FlatTopHexagonClipper",
    ): "The CR117 rename record itself — the section explaining what the name used to mean.",
    (
        "docs/forward_planning/CR105_reconcile_pm_verdict_vocabulary/CR105_reconcile_pm_verdict_vocabulary.md",
        "daily_briefing",
    ): "CR105's audit finding, quoting the state of the field at the time it split DEF129 out.",
    (
        "docs/initial_specs/10_delivery/project_plan.md",
        "daily_briefing",
    ): "The A17 row explaining why the daily-briefing feature was dropped, not planned.",
}


def _spec_files() -> list[Path]:
    return sorted(p for p in DOCS.rglob("*.md") if p.is_file())


def _is_exempt(rel: str, entry: _Vacated) -> bool:
    return any(x in rel for x in _GLOBAL_EXEMPT + entry.exempt_paths)


def _offending_lines(entry: _Vacated) -> list[tuple[str, int, str]]:
    """Every line naming `entry.identifier` that neither marks it dead nor is acknowledged."""
    # Word-boundary match so `daily_briefing` does not also fire on a longer identifier that
    # merely contains it, and so prose about "briefings" in general is left alone.
    pattern = re.compile(rf"(?<![\w]){re.escape(entry.identifier)}(?![\w])")
    offenders: list[tuple[str, int, str]] = []

    for path in _spec_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        if _is_exempt(rel, entry):
            continue
        if (rel, entry.identifier) in ACKNOWLEDGED:
            continue
        for lineno, line in enumerate(
            path.read_text(encoding="utf-8").splitlines(), start=1
        ):
            if not pattern.search(line):
                continue
            lowered = line.lower()
            if any(marker in lowered for marker in _DEATH_MARKERS):
                continue
            offenders.append((rel, lineno, line.strip()))

    return offenders


def test_no_vacated_identifier_is_prescribed_as_current_api() -> None:
    problems: list[str] = []

    for entry in VACATED:
        for rel, lineno, text in _offending_lines(entry):
            problems.append(
                f"{rel}:{lineno} names `{entry.identifier}`, vacated by {entry.vacated_by}.\n"
                f"      {text[:160]}\n"
                f"      Use: {entry.replacement}\n"
                f"      If this line is describing the REMOVAL rather than prescribing the "
                f"identifier, say so on the line (e.g. 'removed by {entry.vacated_by}') or add "
                f"an ACKNOWLEDGED entry with a reason."
            )

    assert not problems, (
        "The spec tree prescribes an identifier that no longer exists. A builder who reads "
        "the spec before the code copies a compile error out of it — which is DEF167 and "
        "DEF171, the defect this guard exists to stop recurring.\n\n" + "\n".join(problems)
    )


def test_the_scanner_actually_finds_things() -> None:
    """Non-vacuity: prove the matcher fires, so a green result means 'clean', not 'no-op'.

    Without this, deleting the identifier from `VACATED`, breaking the glob, or pointing
    `DOCS` at an empty directory would all present as a passing guard.
    """
    assert DOCS.is_dir(), f"docs tree not found at {DOCS}"

    files = _spec_files()
    assert len(files) > 100, f"only {len(files)} spec files found — the glob is broken"

    # The removal records must still exist and must still be recognised as records, or the
    # death-marker mechanism has silently stopped working.
    hits = 0
    for entry in VACATED:
        pattern = re.compile(rf"(?<![\w]){re.escape(entry.identifier)}(?![\w])")
        for path in files:
            rel = path.relative_to(REPO_ROOT).as_posix()
            if _is_exempt(rel, entry):
                continue
            if pattern.search(path.read_text(encoding="utf-8")):
                hits += 1
                break

    assert hits == len(VACATED), (
        f"only {hits} of {len(VACATED)} vacated identifiers appear anywhere in the "
        "non-exempt spec tree. Either the paper trail recording the removal was deleted "
        "(it should not be), or this scanner no longer reads the files it thinks it does."
    )


def test_every_acknowledged_entry_still_applies() -> None:
    """An ACKNOWLEDGED entry that no longer matches anything is stale — delete it.

    Otherwise the escape-hatch list grows monotonically and starts silently excusing files
    that were fixed years ago, which is how a default-deny guard decays into a default-allow.
    """
    stale: list[str] = []

    for (rel, identifier), reason in ACKNOWLEDGED.items():
        path = REPO_ROOT / rel
        if not path.is_file():
            stale.append(f"{rel} (file does not exist) — {reason}")
            continue
        pattern = re.compile(rf"(?<![\w]){re.escape(identifier)}(?![\w])")
        if not pattern.search(path.read_text(encoding="utf-8")):
            stale.append(f"{rel} no longer names `{identifier}` — {reason}")

    assert not stale, (
        "ACKNOWLEDGED carries entries that no longer apply. Remove them so the list keeps "
        "meaning 'these specific mentions were justified':\n  " + "\n  ".join(stale)
    )
