"""DEF215 — who owns the schema on a database that already exists.

The defect was an ORDERING, not a missing check. `init_schema()` ran
`Base.metadata.create_all()` first and only afterwards asked whether
`alembic_version` was present, so the presence check guarded the stamp and not
the create. On an existing database `create_all` therefore still built exactly
the tables the incoming CR had just added — correctly, since it reads the same
`Base.metadata` the migrations were autogenerated from — and then returned
without stamping. Alembic was left behind reality with no record of it, the
first migration that CREATEd one of those tables died on `DuplicateTable`, and
Alembic aborts the whole chain.

Measured on Alpha 2026-08-04: the two migrations AFTER the failing one only
ALTER `journal_entries`, a table `create_all` will never touch because it
already exists, so they never ran — and every journal read on live Alpha
failed on a missing `dedupe_key` column. The outage surfaced in an unrelated,
already-shipped feature rather than in the new one, which is why it cost hours
to place.

These are the assertions nothing made at the time.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
from sqlalchemy import inspect, text

from app.db import session as db_session
from app.db.session import get_engine, init_schema, reset_for_tests

# Deliberately stands up databases at OLDER alembic revisions, where
# `sim_holdings.split_adjusted_at` does not exist yet — the ledger check cannot
# query a schema this file exists to hold at an earlier point.
pytestmark = pytest.mark.allow_ledger_drift

_A_TABLE_A_CR_MIGHT_ADD = "price_history_daily"


@pytest.fixture
def fresh_db_url():
    """A sqlite file this module owns, restored to the suite's own DB after."""
    with tempfile.TemporaryDirectory() as tmp:
        url = f"sqlite:///{Path(tmp) / 'def215.db'}"
        reset_for_tests(url)
        try:
            yield url
        finally:
            reset_for_tests()


def _tables() -> set[str]:
    return set(inspect(get_engine()).get_table_names())


def _rearm() -> None:
    """Clear the per-engine short-circuit so `init_schema()` re-runs.

    White-box on purpose: the guard exists so ten store constructors do not
    each pay two round trips, and every assertion below is about what
    `init_schema` does on its FIRST look at a database.
    """
    db_session._schema_checked_for = None


def test_an_existing_database_gets_no_tables_created_under_it(fresh_db_url) -> None:
    """The inversion, stated directly: with `alembic_version` present, a table
    that `Base.metadata` knows about and the DB lacks must STAY missing.

    That table is what a table-adding CR looks like from this function's point
    of view, and creating it behind Alembic's back is the whole defect —
    Alembic would then try to create it again and take the rest of the chain
    down with it.
    """
    assert _A_TABLE_A_CR_MIGHT_ADD in _tables()
    assert "alembic_version" in _tables(), (
        "fixture precondition: a fresh DB self-stamps, so this one is now "
        "indistinguishable from a deployed database"
    )

    with get_engine().begin() as conn:
        conn.execute(text(f"DROP TABLE {_A_TABLE_A_CR_MIGHT_ADD}"))
    assert _A_TABLE_A_CR_MIGHT_ADD not in _tables()

    _rearm()
    init_schema()

    assert _A_TABLE_A_CR_MIGHT_ADD not in _tables(), (
        "create_all built a table on a database Alembic owns — the next "
        "`alembic upgrade head` dies on DuplicateTable and every migration "
        "after it in the chain silently never runs (DEF215)"
    )


def test_a_fresh_database_still_gets_everything_built_and_stamped(
    fresh_db_url,
) -> None:
    """Non-vacuity, and the case `create_all` actually exists for.

    Without this the test above passes on a function that does nothing at all.
    A sqlite tempfile fixture must still cost one `create_all` rather than a
    per-migration replay, and it must still self-stamp, or a later
    `alembic upgrade head` walks the whole chain against a schema that is
    already there.
    """
    with get_engine().begin() as conn:
        conn.execute(text(f"DROP TABLE {_A_TABLE_A_CR_MIGHT_ADD}"))
        conn.execute(text("DROP TABLE alembic_version"))
    assert "alembic_version" not in _tables()

    _rearm()
    init_schema()

    assert _A_TABLE_A_CR_MIGHT_ADD in _tables()
    assert "alembic_version" in _tables(), "a fresh DB must self-stamp"
    with get_engine().connect() as conn:
        stamped = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
    assert stamped, "stamped, but to nothing"


def test_a_database_behind_head_says_so_by_name(
    fresh_db_url, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """DEF215's outage was silent for as long as it took someone to notice
    journal reads failing: old schema, new code, and nothing anywhere
    comparing the two. One named line with both revisions in it is the
    difference between reading an `UndefinedColumn` traceback and knowing
    which migration never ran."""
    errors: list[tuple[str, dict]] = []
    monkeypatch.setattr(
        db_session.logger, "error", lambda event, **kw: errors.append((event, kw)),
    )

    with get_engine().begin() as conn:
        conn.execute(text("UPDATE alembic_version SET version_num = 'deadbeef0000'"))

    _rearm()
    init_schema()

    assert [e for e, _kw in errors] == ["db_schema_behind_head"], errors
    _event, fields = errors[0]
    assert fields["current_revision"] == "deadbeef0000"
    assert fields["head_revision"] and fields["head_revision"] != "deadbeef0000"


def test_a_database_at_head_reports_nothing(
    fresh_db_url, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The counter-case. A check that fires on every boot is noise, and noise
    is how the next real one gets scrolled past."""
    errors: list[str] = []
    monkeypatch.setattr(
        db_session.logger, "error", lambda event, **kw: errors.append(event),
    )

    _rearm()
    init_schema()

    assert errors == [], "a DB the fixture just stamped to head is not behind it"


# ── DEF215 audit round 1, the two MINORs ────────────────────────────────────


def test_the_behind_head_report_fires_once_per_engine_not_once_per_store(
    fresh_db_url, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Audit r1 MINOR m2. The auditor's AUD-2 removed `_schema_checked_for = engine`
    from the NON-FRESH path only — leaving the fix itself intact — and all 4 tests
    still passed. Nothing pinned the memoisation.

    It guards something real. `init_schema()` is called from 13 store/service
    constructors, so losing that one line means a DB behind head emits
    `db_schema_behind_head` **13 times per process instead of once**. The control
    introduced here specifically to be noticed becomes log spam, and a log nobody
    reads is not a control.
    """
    reports: list[str] = []
    monkeypatch.setattr(
        db_session.logger, "error", lambda event, **kw: reports.append(event),
    )
    with get_engine().begin() as conn:
        conn.execute(text("UPDATE alembic_version SET version_num = 'deadbeef0000'"))

    _rearm()
    for _ in range(13):          # one per real call site
        init_schema()

    assert reports == ["db_schema_behind_head"], (
        f"13 calls produced {len(reports)} reports — the memoisation is gone and the "
        f"control is now spam"
    )


def test_two_threads_initialising_a_fresh_schema_do_not_raise(
    fresh_db_url, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Audit r1 MINOR m1. The submission called this "benign — `checkfirst=True`".
    It is not: `checkfirst` inspects and then creates, without a lock, so two
    threads both see a table missing and both issue `CREATE TABLE`. The auditor
    measured `['OperationalError']` raising out of `init_schema` — the DB ended
    coherent (one `alembic_version` row, all tables), so nothing corrupted, but a
    caller ate an exception at boot.

    Fresh-DB-only and therefore unreachable on Alpha, which carries
    `alembic_version` — but FastAPI runs sync deps in a threadpool, so a first boot
    against an empty database can reach it.

    **A barrier alone does NOT reproduce this**, and the first version of this test
    passed with the lock removed — a survived mutation, not a guard. On sqlite the
    first thread finishes `create_all` before the second is scheduled, so the two
    never overlap. The delay below widens the window `checkfirst` leaves open, which
    is the thing under test: inspect, *then* create, with no lock between them. With
    the lock the second thread parks on it and finds the memo set, so the delay
    changes nothing; without the lock both threads see a missing table and both
    issue `CREATE TABLE`.
    """
    import threading
    import time

    real_create_all = db_session.Base.metadata.create_all

    def _slow_create_all(*args, **kwargs):
        time.sleep(0.2)
        return real_create_all(*args, **kwargs)

    monkeypatch.setattr(db_session.Base.metadata, "create_all", _slow_create_all)

    with get_engine().begin() as conn:
        conn.execute(text(f"DROP TABLE {_A_TABLE_A_CR_MIGHT_ADD}"))
        conn.execute(text("DROP TABLE alembic_version"))
    _rearm()

    barrier = threading.Barrier(2)
    errors: list[BaseException] = []

    def _race() -> None:
        barrier.wait()
        try:
            init_schema()
        except BaseException as exc:      # noqa: BLE001 — the thing under test
            errors.append(exc)

    threads = [threading.Thread(target=_race) for _ in range(2)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    assert errors == [], f"a caller ate {[type(e).__name__ for e in errors]} at boot"
    assert _A_TABLE_A_CR_MIGHT_ADD in _tables()
    with get_engine().connect() as conn:
        rows = conn.execute(text("SELECT version_num FROM alembic_version")).fetchall()
    assert len(rows) == 1, f"double-stamped: {rows}"
