"""CR136 M02 estimator-core tests — offline-numpy known-answer fixtures (literals, provenance in comments), Euler/closed-form identities, N=1/N=2 boundaries, t_eff pins, stdlib-purity guard.

The fixtures below were produced by an implementation that has never seen the
one under test (`backend/scripts/cr136_generate_fixtures.py`, numpy, written
from the specification). That independence is the whole point of Rev 4
estimator pin 7: a test that compares `ewma_covariance` against a second copy of
`ewma_covariance` proves only that the copy was faithful.

Where a closed form exists, it is preferred over a literal — a closed form
cannot be silently regenerated to match a broken implementation.
"""

from __future__ import annotations

import ast
import math
from pathlib import Path

import pytest

from app.trading_math import (
    BAD_MONTH_Z,
    EWMA_LAMBDA,
    TRADING_DAYS_PER_MONTH,
    TRADING_DAYS_PER_YEAR,
    annualize_vol,
    append_zero_row,
    bad_month,
    beta_r2,
    dr_squared,
    euler_contributions,
    ewma_covariance,
    hhi_effective_n,
    mcr,
    portfolio_sigma,
    scenario_replay,
    se_beta,
    se_sigma,
    t_eff,
    tracking_error,
)

# ── FIXTURES — generated by backend/scripts/cr136_generate_fixtures.py ───────
#
# Generated 2026-08-02, numpy 2.4.4, lambda=0.97. Independent numpy
# implementation; the shipped estimator is NOT imported by the generator
# (Rev 4 estimator pin 7). Re-running the script must reproduce these exactly.

# (a) EWMA known answer, N=3, T=8. No structure is asked of this one — it is a
#     full-precision known answer for the estimator itself.
FIXTURE_A_RETURNS = [
    [0.0120, -0.0080, 0.0210, -0.0150, 0.0040, 0.0180, -0.0110, 0.0070],
    [0.0035, 0.0090, -0.0025, 0.0110, -0.0060, 0.0015, 0.0075, -0.0040],
    [-0.0050, 0.0020, 0.0130, 0.0060, -0.0090, 0.0045, 0.0025, 0.0100],
]
FIXTURE_A_COV = [
    [0.00015935544393620374, -5.277211370599834e-05, 1.4201098255339979e-05],
    [-5.277211370599834e-05, 3.5333325461917245e-05, 1.613456272253337e-06],
    [1.4201098255339979e-05, 1.613456272253337e-06, 4.564739802178625e-05],
]

# (b) NON-UNIFORM correlation structure (Rev 4 F8). A uniform-ρ fixture passes
#     identically even when the estimator is fully degenerate, so it cannot
#     detect the failure mode that matters. Measured EWMA correlations of the
#     emitted matrix:
#         rho(0,1) = +0.724059     <- the required pair >= +0.6
#         rho(0,2) = -0.450633     <- the required pair <= -0.3
#         rho(0,3) = +0.060150     <- the required pair with |rho| <= 0.25
#         rho(1,2) = -0.691095
#         rho(1,3) = -0.104253
#         rho(2,3) = -0.434511
#     Deliberately moderate (condition number ~40) rather than a near-singular
#     ±0.99 structure, which would agree with a degenerate estimator for the
#     wrong reason. Asset 2's NEGATIVE risk contribution below is correct and
#     intentional: a negatively-correlated holding reduces portfolio risk.
FIXTURE_B_RETURNS = [
    [0.0120, -0.0080, 0.0210, -0.0150, 0.0040, 0.0180, -0.0110, 0.0070],
    [0.0120, -0.0030, 0.0160, -0.0050, 0.0140, 0.0100, 0.0100, 0.0150],
    [-0.0160, 0.0160, -0.0030, 0.0150, -0.0180, 0.0130, 0.0090, -0.0010],
    [0.0080, -0.0080, 0.0120, 0.0130, 0.0100, -0.0130, -0.0140, -0.0160],
]
FIXTURE_B_WEIGHTS = [0.4, 0.3, 0.2, 0.1]
FIXTURE_B_COV = [
    [0.00015935544393620374, 6.836196408547498e-05, -7.127283784717741e-05, 9.197653765057324e-06],
    [6.836196408547498e-05, 5.593893431758655e-05, -6.476078716011367e-05, -9.444955024812782e-06],
    [-7.127283784717741e-05, -6.476078716011367e-05, 0.00015697643372922584, -6.594361318895122e-05],
    [9.197653765057324e-06, -9.444955024812782e-06, -6.594361318895122e-05, 0.00014672689860181377],
]
FIXTURE_B_SIGMA = 0.0057481296776840645
FIXTURE_B_DR2 = 3.6689961793885644
FIXTURE_B_CONTRIBUTIONS = [
    0.8585209380620377, 0.27447551006633814, -0.1400469084298056, 0.007050460301429752,
]
FIXTURE_B_MCR = [
    0.0123372242074689, 0.005259069417365965, -0.00402503895306634, 0.0004052696009998169,
]

# (d) Joint matrix: 3 risky legs + the benchmark leg (last row) at weight
#     exactly 0.0. Chosen to be representative rather than merely valid —
#     beta ~ 1.23 and R^2 ~ 0.72, a book the market mostly but not entirely
#     explains. At R^2 ~ 0.99 the residual variance is floating dust and
#     se_beta would only ever be exercised on its clamp path.
FIXTURE_D_RETURNS = [
    [-0.0050, 0.0200, -0.0150, -0.0200, 0.0190, 0.0070, -0.0170, -0.0060],
    [0.0000, 0.0010, -0.0130, -0.0080, 0.0020, 0.0010, 0.0170, 0.0120],
    [-0.0020, 0.0190, 0.0030, -0.0090, 0.0070, 0.0170, 0.0200, 0.0070],
    [-0.0030, 0.0070, -0.0140, -0.0030, 0.0060, 0.0060, 0.0010, 0.0000],
]
FIXTURE_D_WEIGHTS = [0.5, 0.3, 0.2, 0.0]
FIXTURE_D_B_INDEX = 3
FIXTURE_D_COV = [
    [0.00021567755564055077, 6.442630564810371e-06, 6.089481860477701e-05, 6.813304149460524e-05],
    [6.442630564810371e-06, 8.392175629587396e-05, 5.244164867309354e-05, 2.98090133642107e-05],
    [6.089481860477701e-05, 5.244164867309354e-05, 9.387607915444295e-05, 3.4766975304044915e-05],
    [6.813304149460524e-05, 2.98090133642107e-05, 3.4766975304044915e-05, 4.050358349113875e-05],
]
FIXTURE_D_BETA = 1.2335357889581666
FIXTURE_D_R2 = 0.7197143388654089
FIXTURE_D_VAR_P = 8.56321408741138e-05
FIXTURE_D_VAR_B = 4.050358349113875e-05
FIXTURE_D_TE_DAILY = 0.005119617635185557
FIXTURE_D_T_EFF = 62.897
FIXTURE_D_SE_BETA = 0.09706376907626803

# ── end fixtures ────────────────────────────────────────────────────────────


def _uniform_rho_cov(n: int, sigma: float, rho: float) -> list[list[float]]:
    """(c) Uniform-ρ covariance, built analytically in-test — no generator
    involved, so the closed forms below check the module against algebra rather
    than against another program."""
    var = sigma * sigma
    return [
        [var if i == j else rho * var for j in range(n)]
        for i in range(n)
    ]


# ── 1-3. The estimator ──────────────────────────────────────────────────────


def test_the_non_uniform_fixtures_are_the_estimator_own_output() -> None:
    """Rev 4 F8's point is that a uniform-ρ fixture agrees with a fully
    degenerate estimator. That only bites if the non-uniform RETURNS are
    actually fed through `ewma_covariance` — checking the metrics against a
    checked-in matrix leaves the estimator itself untested on that structure."""
    cov_b = ewma_covariance(FIXTURE_B_RETURNS, EWMA_LAMBDA)
    for i in range(4):
        for j in range(4):
            assert abs(cov_b[i][j] - FIXTURE_B_COV[i][j]) <= 1e-15, (i, j)

    cov_d = ewma_covariance(FIXTURE_D_RETURNS, EWMA_LAMBDA)
    for i in range(4):
        for j in range(4):
            assert abs(cov_d[i][j] - FIXTURE_D_COV[i][j]) <= 1e-15, (i, j)

    # ...and the structure the fixture exists for really is non-uniform.
    rho = [
        [cov_b[i][j] / math.sqrt(cov_b[i][i] * cov_b[j][j]) for j in range(4)]
        for i in range(4)
    ]
    pairs = [rho[i][j] for i in range(4) for j in range(i + 1, 4)]
    assert any(r >= 0.6 for r in pairs), pairs
    assert any(r <= -0.3 for r in pairs), pairs
    assert any(abs(r) <= 0.25 for r in pairs), pairs


def test_ewma_covariance_known_answer() -> None:
    cov = ewma_covariance(FIXTURE_A_RETURNS, EWMA_LAMBDA)
    assert len(cov) == 3
    for i in range(3):
        assert len(cov[i]) == 3
        for j in range(3):
            assert abs(cov[i][j] - FIXTURE_A_COV[i][j]) <= 1e-15, (i, j)
    # Symmetric by construction, not by luck.
    for i in range(3):
        for j in range(3):
            assert cov[i][j] == cov[j][i]


def test_ewma_covariance_single_asset_closed_form() -> None:
    """Two observations, one asset: the weighted population variance collapses
    to `λ/(1+λ)² · Δ²`, which is checkable by hand."""
    cov = ewma_covariance([[0.0, 0.02]], EWMA_LAMBDA)
    expected = EWMA_LAMBDA / (1.0 + EWMA_LAMBDA) ** 2 * 0.0004
    assert abs(cov[0][0] - expected) < 1e-18
    assert abs(expected - 9.99768e-05) < 1e-9


def test_ewma_covariance_t1_is_the_zero_matrix() -> None:
    """The formula's own output for a single observation — not a special case,
    and not a substitute for the T >= 126 floor, which is the caller's."""
    assert ewma_covariance([[0.01], [0.02]]) == [[0.0, 0.0], [0.0, 0.0]]


def test_ewma_covariance_raises() -> None:
    with pytest.raises(ValueError):
        ewma_covariance([])
    with pytest.raises(ValueError):
        ewma_covariance([[]])
    with pytest.raises(ValueError):
        ewma_covariance([[0.01, 0.02], [0.01]])          # ragged
    for bad_lam in (0.0, 1.0, -0.1, 1.5):
        with pytest.raises(ValueError):
            ewma_covariance(FIXTURE_A_RETURNS, bad_lam)


def test_time_order_is_newest_last() -> None:
    """Guards the silent oldest-last misreading: with exponential weights the
    same observations in reverse order MUST give a different matrix. An
    estimator that ignored order would pass every other test in this file."""
    reversed_rows = [list(reversed(row)) for row in FIXTURE_A_RETURNS]
    cov = ewma_covariance(reversed_rows, EWMA_LAMBDA)
    assert abs(cov[0][0] - FIXTURE_A_COV[0][0]) > 1e-9


# ── 4. t_eff ────────────────────────────────────────────────────────────────


def test_t_eff_pins() -> None:
    # Asymptote (1+λ)/(1−λ), reached well before t=5000.
    assert round(t_eff(0.94, 5000), 3) == 32.333
    assert round(t_eff(0.97, 5000), 3) == 65.667
    assert round(t_eff(0.98, 5000), 3) == 99.000
    # Rev 4's sufficiency table: T_eff ≈ 62.9 at the T=126 floor, 65.61 at 252.
    assert abs(t_eff(0.97, 126) - 62.897) < 1e-3
    assert abs(t_eff(0.97, 252) - 65.61) < 5e-3


def test_t_eff_direct_sum_matches_the_closed_form() -> None:
    """The module computes the direct sum; the closed form is the independent
    check. A formula that checks itself checks nothing."""
    for lam in (0.90, 0.94, 0.97, 0.98):
        for t in (1, 2, 5, 63, 126, 252, 504):
            closed = ((1.0 + lam) / (1.0 - lam)) * (
                (1.0 - lam ** t) / (1.0 + lam ** t)
            )
            assert abs(t_eff(lam, t) - closed) < 1e-9, (lam, t)


def test_t_eff_raises() -> None:
    with pytest.raises(ValueError):
        t_eff(0.97, 0)
    with pytest.raises(ValueError):
        t_eff(0.97, -1)
    with pytest.raises(ValueError):
        t_eff(1.0, 126)


# ── 5. portfolio_sigma ──────────────────────────────────────────────────────


def test_portfolio_sigma() -> None:
    assert abs(
        portfolio_sigma(FIXTURE_B_WEIGHTS, FIXTURE_B_COV) - FIXTURE_B_SIGMA
    ) < 1e-15


def test_portfolio_sigma_validates_its_matrix() -> None:
    asymmetric = [[1.0, 0.5], [0.4, 1.0]]
    with pytest.raises(ValueError, match="symmetric"):
        portfolio_sigma([0.5, 0.5], asymmetric)
    with pytest.raises(ValueError):
        portfolio_sigma([0.5, 0.5, 0.0], [[1.0, 0.0], [0.0, 1.0]])   # len mismatch
    with pytest.raises(ValueError):
        portfolio_sigma([0.5, 0.5], [[1.0, 0.0], [0.0]])             # ragged row
    with pytest.raises(ValueError):
        portfolio_sigma([], [])


def test_portfolio_sigma_rejects_a_non_psd_matrix() -> None:
    """A negative quadratic form beyond floating dust is a wrong number, and a
    wrong number must not ship (CR040)."""
    with pytest.raises(ValueError, match="positive semi-definite"):
        portfolio_sigma([1.0, 1.0], [[1.0, -2.0], [-2.0, 1.0]])


def test_the_psd_dust_clamp_is_exercised_on_the_clamping_side() -> None:
    """Both sides of the boundary, not just the raise. A quadratic form that is
    negative only by floating dust is a rounding artefact of an otherwise
    healthy matrix, and raising on it would blank a whole book."""
    dust = -5e-13
    assert portfolio_sigma([1.0], [[dust]]) == 0.0
    with pytest.raises(ValueError):
        portfolio_sigma([1.0], [[-5e-12]])


def test_the_tracking_error_clamp_is_exercised_on_real_dust() -> None:
    """(0.2, 0.2, 1.0) gives a radicand of EXACTLY 0.0 and never reaches the
    clamp; this case does."""
    assert tracking_error(0.2, 0.2, 1.0) == 0.0
    nudged = tracking_error(0.2, 0.2, 1.0 + 5e-12)
    assert nudged == 0.0
    with pytest.raises(ValueError, match="inconsistent"):
        tracking_error(0.2, 0.2, 1.0 + 1e-6)


# ── 6. Euler identity with the cash row ─────────────────────────────────────


def test_euler_sum_with_cash_row() -> None:
    cov = append_zero_row(FIXTURE_B_COV)
    w = [0.3, 0.225, 0.15, 0.075, 0.25]        # invested weights x 0.75, + 25% cash
    assert abs(sum(w) - 1.0) < 1e-15
    contribs = euler_contributions(w, cov)
    assert abs(math.fsum(contribs) - 1.0) <= 1e-9
    assert contribs[-1] == 0.0, "cash contributes EXACTLY zero, not approximately"


def test_the_benchmark_leg_contributes_exactly_zero() -> None:
    contribs = euler_contributions(FIXTURE_D_WEIGHTS, FIXTURE_D_COV)
    assert contribs[FIXTURE_D_B_INDEX] == 0.0
    assert abs(math.fsum(contribs) - 1.0) <= 1e-9


def test_euler_contributions_match_the_independent_fixture() -> None:
    contribs = euler_contributions(FIXTURE_B_WEIGHTS, FIXTURE_B_COV)
    for got, want in zip(contribs, FIXTURE_B_CONTRIBUTIONS):
        assert abs(got - want) < 1e-15
    assert contribs[2] < 0.0, (
        "the fixture's negatively-correlated holding must show a NEGATIVE risk "
        "share — clamping it to zero would hide the one thing it teaches"
    )


# ── 7. MCR ──────────────────────────────────────────────────────────────────


def test_mcr() -> None:
    values = mcr(FIXTURE_B_WEIGHTS, FIXTURE_B_COV)
    for got, want in zip(values, FIXTURE_B_MCR):
        assert abs(got - want) < 1e-15
    identity = math.fsum(
        FIXTURE_B_WEIGHTS[i] * values[i] for i in range(len(values))
    )
    assert abs(identity - FIXTURE_B_SIGMA) < 1e-12


# ── 8. DR² ──────────────────────────────────────────────────────────────────


def test_dr_squared_uniform_rho_closed_form() -> None:
    n = 10
    w = [1.0 / n] * n
    for rho, pinned in ((0.8, 1.22), (0.2, 3.57)):
        cov = _uniform_rho_cov(n, 0.02, rho)
        got = dr_squared(w, cov)
        closed = 1.0 / (1.0 / n + (1.0 - 1.0 / n) * rho)
        assert abs(got - closed) < 1e-9
        assert round(got, 2) == pinned


def test_dr_squared_non_uniform_fixture() -> None:
    assert abs(dr_squared(FIXTURE_B_WEIGHTS, FIXTURE_B_COV) - FIXTURE_B_DR2) < 1e-13


def test_dr_squared_is_cash_invariant() -> None:
    """Rev 4 F9: cash scales σₚ and the weighted-vol numerator identically, so
    DR² must not move at all. If it did, a user parking 40% in cash would watch
    'effective independent bets' change for a reason unconnected to what they
    hold."""
    invested = dr_squared(FIXTURE_B_WEIGHTS, FIXTURE_B_COV)
    with_cash = dr_squared(
        [w * 0.6 for w in FIXTURE_B_WEIGHTS] + [0.4],
        append_zero_row(FIXTURE_B_COV),
    )
    assert abs(with_cash - invested) < 1e-12


# ── 9-10. Beta / R² / tracking error ────────────────────────────────────────


def test_beta_r2_joint_fixture() -> None:
    beta, r2 = beta_r2(FIXTURE_D_WEIGHTS, FIXTURE_D_COV, FIXTURE_D_B_INDEX)
    assert abs(beta - FIXTURE_D_BETA) < 1e-13
    assert abs(r2 - FIXTURE_D_R2) < 1e-13
    assert 0.0 <= r2 <= 1.0


def test_beta_r2_requires_a_zero_weight_benchmark_leg() -> None:
    w = list(FIXTURE_D_WEIGHTS)
    w[FIXTURE_D_B_INDEX] = 0.1
    with pytest.raises(ValueError, match="estimation leg"):
        beta_r2(w, FIXTURE_D_COV, FIXTURE_D_B_INDEX)


def test_beta_r2_rejects_a_flat_benchmark_and_a_bad_index() -> None:
    cov = [row[:] for row in FIXTURE_D_COV]
    for i in range(4):
        cov[i][FIXTURE_D_B_INDEX] = 0.0
        cov[FIXTURE_D_B_INDEX][i] = 0.0
    with pytest.raises(ValueError, match="benchmark variance"):
        beta_r2(FIXTURE_D_WEIGHTS, cov, FIXTURE_D_B_INDEX)
    with pytest.raises(ValueError, match="out of range"):
        beta_r2(FIXTURE_D_WEIGHTS, FIXTURE_D_COV, 4)


def test_tracking_error_agrees_with_the_joint_fixture() -> None:
    beta, _ = beta_r2(FIXTURE_D_WEIGHTS, FIXTURE_D_COV, FIXTURE_D_B_INDEX)
    var_p = portfolio_sigma(FIXTURE_D_WEIGHTS, FIXTURE_D_COV) ** 2
    assert abs(var_p - FIXTURE_D_VAR_P) < 1e-18
    # var_b comes from the ESTIMATOR here, not from the checked-in matrix —
    # comparing two literals to each other would prove nothing.
    computed = ewma_covariance(FIXTURE_D_RETURNS, EWMA_LAMBDA)
    assert abs(computed[FIXTURE_D_B_INDEX][FIXTURE_D_B_INDEX] - FIXTURE_D_VAR_B) < 1e-20
    te = tracking_error(math.sqrt(FIXTURE_D_VAR_P), math.sqrt(FIXTURE_D_VAR_B), beta)
    assert abs(te - FIXTURE_D_TE_DAILY) < 1e-12


def test_tracking_error_pin() -> None:
    """Rev 4's stated identity check: σₚ=26.20%, σ_b=15.87%, β=1.301 → 16.82%."""
    assert round(100 * tracking_error(0.2620, 0.1587, 1.301), 2) == 16.82
    assert tracking_error(0.2, 0.2, 1.0) == 0.0
    with pytest.raises(ValueError, match="inconsistent"):
        tracking_error(0.05, 0.20, 2.0)


# ── 11. HHI → effective N ───────────────────────────────────────────────────


def test_hhi_effective_n() -> None:
    assert abs(hhi_effective_n([0.1] * 10) - 10.0) < 1e-9
    assert hhi_effective_n([1.0]) == 1.0
    assert abs(hhi_effective_n([0.9, 0.1]) - 1.0 / 0.82) < 1e-9
    with pytest.raises(ValueError):
        hhi_effective_n([])
    with pytest.raises(ValueError):
        hhi_effective_n([0.0, 0.0])


# ── 12-13. Bad month, scenario replay ───────────────────────────────────────


def test_bad_month_pins() -> None:
    for sigma in (0.10, 0.262, 0.35):
        assert bad_month(sigma) == BAD_MONTH_Z * sigma * math.sqrt(
            TRADING_DAYS_PER_MONTH / TRADING_DAYS_PER_YEAR
        )
    # Rev 4 acceptance at σ = 26.2%: 2.71 / 6.07 / 12.44 % for 1d / 1w / 1mo.
    # Only the monthly figure is a module function; the other two are the
    # √-time family stated inline, because the product ships only the month.
    assert round(100 * bad_month(0.262), 2) == 12.44
    assert round(100 * 1.645 * 0.262 * math.sqrt(1 / 252), 2) == 2.71
    assert round(100 * 1.645 * 0.262 * math.sqrt(5 / 252), 2) == 6.07


def test_scenario_replay() -> None:
    assert round(scenario_replay(1.301, -0.339), 4) == -0.4410
    assert scenario_replay(0.0, -0.339) == 0.0


# ── 14-15. Standard errors ──────────────────────────────────────────────────


def test_se_sigma() -> None:
    for sigma, te in ((0.20, 65.667), (0.35, 62.897)):
        assert se_sigma(sigma, te) == sigma / math.sqrt(2.0 * te)
    assert round(se_sigma(0.20, 65.667), 6) == 0.017452
    with pytest.raises(ValueError):
        se_sigma(0.20, 0.0)
    with pytest.raises(ValueError):
        se_sigma(0.20, -1.0)


def test_se_sigma_is_not_the_equal_weight_formula() -> None:
    """Rev 4: publishing σ/√(2T) under EWMA understates the true sampling SE by
    ~27%. The signature makes the wrong formula unreachable — there is no T to
    pass — so this pins the magnitude of what would have been lost."""
    naive_at_floor = 0.20 / math.sqrt(2.0 * 126)
    correct_at_floor = se_sigma(0.20, t_eff(EWMA_LAMBDA, 126))
    assert correct_at_floor > naive_at_floor
    # At the T=126 sufficiency floor the naive formula understates by 29.3%.
    assert round(100 * (1 - naive_at_floor / correct_at_floor), 1) == 29.3
    # Rev 4's headline "~27%" is the asymptotic case (T_eff → (1+λ)/(1−λ)),
    # which lands at 27.8%. Both are stated so neither figure can drift into
    # standing for the other.
    correct_asymptotic = se_sigma(0.20, (1 + EWMA_LAMBDA) / (1 - EWMA_LAMBDA))
    assert round(100 * (1 - naive_at_floor / correct_asymptotic), 1) == 27.8


def test_se_beta() -> None:
    got = se_beta(FIXTURE_D_VAR_P, FIXTURE_D_VAR_B, FIXTURE_D_BETA, FIXTURE_D_T_EFF)
    assert abs(got - FIXTURE_D_SE_BETA) < 1e-12

    # R² → 1: a book that IS the benchmark has zero residual variance, and
    # floating error can push the subtraction a hair below zero. That must
    # clamp, not raise.
    var_b, beta = FIXTURE_D_VAR_B, 1.0
    dust = beta * beta * var_b - 1e-20
    assert dust - beta * beta * var_b < 0.0, "vacuity guard — this must be negative"
    assert se_beta(dust, var_b, beta, 60.0) == 0.0

    with pytest.raises(ValueError):
        se_beta(0.0001, 0.0, 1.0, 60.0)
    with pytest.raises(ValueError):
        se_beta(0.0001, -0.0002, 1.0, 60.0)
    with pytest.raises(ValueError):
        se_beta(0.0001, 0.0002, 1.0, 0.0)


def test_se_beta_clamp_is_bounded_not_unbounded() -> None:
    """The clamp exists for floating dust, not for arbitrary inconsistency.
    var_p, var_b and beta always come from the SAME Σ in real use, so the
    residual is non-negative by Cauchy–Schwarz; a residual negative by more than
    dust means the caller mixed matrices, and answering that with a confident
    SE of 0.0 is the silent-wrong-number path CR040 forbids."""
    with pytest.raises(ValueError, match="mutually inconsistent"):
        se_beta(0.0001, 0.0002, 1.0, 60.0)          # residual -1e-4, off by 2.5e11 dust


def test_no_metric_accepts_a_non_finite_input() -> None:
    """NaN is invisible to every guard in this module — `nan > x`, `nan < x` and
    `nan <= x` are all False — so without an explicit screen one non-finite
    input propagates a NaN through every metric, and that NaN serialises to the
    same `null` the uncertainty contract uses for "not enough data"."""
    nan, inf = float("nan"), float("inf")

    for bad in (nan, inf, -inf):
        with pytest.raises(ValueError, match="finite"):
            ewma_covariance([[0.01, bad, 0.02]])
        with pytest.raises(ValueError, match="finite"):
            portfolio_sigma([1.0], [[bad]])
        with pytest.raises(ValueError, match="finite"):
            portfolio_sigma([bad], [[0.0004]])
        with pytest.raises(ValueError, match="finite"):
            euler_contributions([1.0], [[bad]])
        with pytest.raises(ValueError, match="finite"):
            mcr([1.0], [[bad]])
        with pytest.raises(ValueError, match="finite"):
            dr_squared([1.0], [[bad]])
        with pytest.raises(ValueError, match="finite"):
            beta_r2([1.0, 0.0], [[0.0004, 0.0], [0.0, bad]], 1)
        with pytest.raises(ValueError, match="finite"):
            tracking_error(bad, 0.15, 1.0)
        with pytest.raises(ValueError, match="finite"):
            hhi_effective_n([0.5, bad])
        with pytest.raises(ValueError, match="finite"):
            bad_month(bad)
        with pytest.raises(ValueError, match="finite"):
            scenario_replay(bad, -0.339)
        with pytest.raises(ValueError, match="finite"):
            se_sigma(bad, 62.9)
        with pytest.raises(ValueError, match="finite"):
            annualize_vol(bad)

    # se_beta is the one that failed WORST without the screen: max(0.0, nan) is
    # 0.0, so a NaN variance produced a confidently zero standard error rather
    # than a NaN anyone would notice.
    with pytest.raises(ValueError, match="finite"):
        se_beta(nan, 0.0002, 1.0, 60.0)


# ── 16. append_zero_row ─────────────────────────────────────────────────────


def test_append_zero_row_refuses_an_empty_matrix() -> None:
    """`[[0.0]]` would be a one-leg riskless portfolio, which is a plausible
    number rather than an error — the worst kind of wrong answer."""
    with pytest.raises(ValueError):
        append_zero_row([])


def test_append_zero_row() -> None:
    source = [[1.0, 0.5], [0.5, 2.0]]
    out = append_zero_row(source)
    assert len(out) == 3
    assert all(len(row) == 3 for row in out)
    assert out[0][:2] == [1.0, 0.5]
    assert out[1][:2] == [0.5, 2.0]
    assert out[2] == [0.0, 0.0, 0.0]
    assert [row[2] for row in out] == [0.0, 0.0, 0.0]
    assert source == [[1.0, 0.5], [0.5, 2.0]], "input must not be mutated"
    out[0][0] = 99.0
    assert source[0][0] == 1.0, "the returned matrix must not alias the input"


# ── 17-19. Boundaries ───────────────────────────────────────────────────────


def test_n1_boundary() -> None:
    """Rev 4 small-books pin: a one-position book produces defined outputs, not
    NaN — σₚ is the holding's own vol, DR² is exactly 1, the share is 100%."""
    w, cov = [1.0], [[0.0004]]
    assert portfolio_sigma(w, cov) == 0.02
    assert dr_squared(w, cov) == 1.0
    assert euler_contributions(w, cov) == [1.0]
    assert abs(mcr(w, cov)[0] - 0.02) < 1e-17


def test_n2_boundary() -> None:
    """N=2 is where the removed Ledoit–Wolf estimator was degenerate (23% of
    seeds hard-NaN). Without shrinkage there is nothing special about it."""
    returns = [
        [0.0120, -0.0080, 0.0210, -0.0150, 0.0040, 0.0180, -0.0110, 0.0070],
        [-0.0160, 0.0160, -0.0030, 0.0150, -0.0180, 0.0130, 0.0090, -0.0010],
    ]
    cov = ewma_covariance(returns)
    w = [0.6, 0.4]
    sigma = portfolio_sigma(w, cov)
    joint = append_zero_row(cov)
    beta, r2 = beta_r2([0.6, 0.0, 0.0], [[cov[0][0], cov[0][1], 0.0],
                                         [cov[0][1], cov[1][1], 0.0],
                                         [0.0, 0.0, cov[1][1]]], 2)
    teff = t_eff(EWMA_LAMBDA, 8)
    for value in (
        sigma,
        dr_squared(w, cov),
        *euler_contributions(w, cov),
        *mcr(w, cov),
        hhi_effective_n(w),
        bad_month(annualize_vol(sigma)),
        annualize_vol(sigma),
        beta,
        r2,
        teff,
        se_sigma(sigma, teff),
        se_beta(sigma * sigma, cov[1][1], beta, teff),
        tracking_error(sigma, math.sqrt(cov[1][1]), beta),
        scenario_replay(beta, -0.339),
        *[v for row in joint for v in row],
    ):
        assert math.isfinite(value)
    assert abs(math.fsum(euler_contributions(w, cov)) - 1.0) <= 1e-9


def test_zero_risk_inputs_raise() -> None:
    zero_w = [0.0, 0.0, 0.0, 0.0]
    for fn in (euler_contributions, mcr, dr_squared):
        with pytest.raises(ValueError):
            fn(zero_w, FIXTURE_B_COV)
    zero_cov = [[0.0] * 4 for _ in range(4)]
    for fn in (euler_contributions, mcr, dr_squared):
        with pytest.raises(ValueError):
            fn(FIXTURE_B_WEIGHTS, zero_cov)


def test_annualize_vol() -> None:
    assert annualize_vol(0.0165) == 0.0165 * math.sqrt(252)
    assert TRADING_DAYS_PER_YEAR == 252
    assert TRADING_DAYS_PER_MONTH == 21
    assert BAD_MONTH_Z == 1.645
    assert EWMA_LAMBDA == 0.97


# ── 20. Package contract ────────────────────────────────────────────────────


def test_stdlib_purity_guard() -> None:
    """`trading_math` is copy-portable by contract: stdlib only, no `app`
    imports, no numpy. Asserted structurally rather than trusted, because the
    contract is a comment in `__init__.py` and comments do not fail builds."""
    from app.trading_math import portfolio_risk

    source = Path(portfolio_risk.__file__).read_text()
    tree = ast.parse(source)
    imported: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.level > 0:          # relative — inside the package, allowed
                continue
            imported.append(node.module or "")

    assert imported, "vacuity guard — the parse found no imports at all"
    for name in imported:
        root = name.split(".")[0]
        assert root in {"math", "__future__"}, f"disallowed import: {name}"
    assert not any(n.startswith("numpy") for n in imported)
    assert not any(n.startswith("app") for n in imported)


def test_no_shrinkage_anywhere() -> None:
    """Rev 4 estimator pin 1 removed Ledoit–Wolf entirely — not disabled, not
    stubbed. It suppressed the correlated-cluster alarm this feature exists to
    raise (89.0% of windows fired unshrunk vs 30.1% shrunk) and divided by zero
    on a cash row."""
    from app.trading_math import portfolio_risk

    tree = ast.parse(Path(portfolio_risk.__file__).read_text())

    # Every identifier the module actually defines or references, from the AST —
    # so the prose that explains WHY shrinkage is absent cannot trip the guard,
    # and no amount of rephrasing that prose can weaken it either.
    identifiers: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            identifiers.append(node.name)
        elif isinstance(node, ast.Name):
            identifiers.append(node.id)
        elif isinstance(node, ast.Attribute):
            identifiers.append(node.attr)
        elif isinstance(node, ast.arg):
            identifiers.append(node.arg)

    assert identifiers, "vacuity guard — the parse found no identifiers at all"
    assert "ewma_covariance" in identifiers, "vacuity guard — wrong module parsed"
    for name in identifiers:
        lowered = name.lower()
        assert "shrink" not in lowered, name
        assert "ledoit" not in lowered, name
        assert "lw_" not in lowered, name
