"""initial schema

Revision ID: e355c2468b2a
Revises: 
Create Date: 2026-05-11 21:20:11.158280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401 — exposes Uuid / JsonB to autogenerated DDL


# revision identifiers, used by Alembic.
revision: str = 'e355c2468b2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activations',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('activation_method', sa.String(), nullable=False),
    sa.Column('triggering_lesson_id', sa.String(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_activation_user_agent')
    )
    op.create_index(op.f('ix_agent_activations_user_id'), 'agent_activations', ['user_id'], unique=False)
    op.create_table('auth_challenges',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_challenges_target'), 'auth_challenges', ['target'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('reference_id', app.db.base.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('agents_involved', app.db.base.JsonB(), nullable=False),
    sa.Column('mandate_version', sa.Integer(), nullable=False),
    sa.Column('tags', app.db.base.JsonB(), nullable=False),
    sa.Column('user_note', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('payload', app.db.base.JsonB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_type'), 'journal_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_journal_entries_ticker'), 'journal_entries', ['ticker'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('lessons_progress',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quiz_attempts', sa.Integer(), nullable=False),
    sa.Column('quiz_passed', sa.Boolean(), nullable=False),
    sa.Column('last_quiz_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lessons_user_lesson')
    )
    op.create_index(op.f('ix_lessons_progress_user_id'), 'lessons_progress', ['user_id'], unique=False)
    op.create_table('mandates',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('snapshot', app.db.base.JsonB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_mandate_user_version')
    )
    op.create_index(op.f('ix_mandates_user_id'), 'mandates', ['user_id'], unique=False)
    op.create_table('overlay_edit_counts',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_overlay_count_user_agent')
    )
    op.create_index(op.f('ix_overlay_edit_counts_user_id'), 'overlay_edit_counts', ['user_id'], unique=False)
    op.create_table('room_runs',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mandate_version', sa.Integer(), nullable=False),
    sa.Column('model_tier', sa.String(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('transcript', app.db.base.JsonB(), nullable=False),
    sa.Column('verdict', app.db.base.JsonB(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_runs_ticker'), 'room_runs', ['ticker'], unique=False)
    op.create_index(op.f('ix_room_runs_user_id'), 'room_runs', ['user_id'], unique=False)
    op.create_table('sim_portfolios',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_portfolios_user_id'), 'sim_portfolios', ['user_id'], unique=True)
    op.create_table('user_overlays',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('plain_english', sa.String(), nullable=False),
    sa.Column('based_on_session', app.db.base.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', 'version', name='uq_overlay_user_agent_version')
    )
    op.create_index(op.f('ix_user_overlays_user_id'), 'user_overlays', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('apple_id', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('hms_unionid', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('anonymous_session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_user_id', app.db.base.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_device_user_id'), 'users', ['device_user_id'], unique=False)
    op.create_table('sim_holdings',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('portfolio_id', app.db.base.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['sim_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_holding_portfolio_ticker')
    )
    op.create_table('sim_trades',
    sa.Column('id', app.db.base.Uuid(), nullable=False),
    sa.Column('user_id', app.db.base.Uuid(), nullable=False),
    sa.Column('portfolio_id', app.db.base.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stop', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('target', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verdict_ref', app.db.base.Uuid(), nullable=True),
    sa.Column('realised_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['sim_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_trades_ticker'), 'sim_trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_sim_trades_user_id'), 'sim_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_trades_user_id'), table_name='sim_trades')
    op.drop_index(op.f('ix_sim_trades_ticker'), table_name='sim_trades')
    op.drop_table('sim_trades')
    op.drop_table('sim_holdings')
    op.drop_index(op.f('ix_users_device_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_overlays_user_id'), table_name='user_overlays')
    op.drop_table('user_overlays')
    op.drop_index(op.f('ix_sim_portfolios_user_id'), table_name='sim_portfolios')
    op.drop_table('sim_portfolios')
    op.drop_index(op.f('ix_room_runs_user_id'), table_name='room_runs')
    op.drop_index(op.f('ix_room_runs_ticker'), table_name='room_runs')
    op.drop_table('room_runs')
    op.drop_index(op.f('ix_overlay_edit_counts_user_id'), table_name='overlay_edit_counts')
    op.drop_table('overlay_edit_counts')
    op.drop_index(op.f('ix_mandates_user_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_lessons_progress_user_id'), table_name='lessons_progress')
    op.drop_table('lessons_progress')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_ticker'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_type'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_auth_challenges_target'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    op.drop_index(op.f('ix_agent_activations_user_id'), table_name='agent_activations')
    op.drop_table('agent_activations')
    # ### end Alembic commands ###
