"""Auth schemas — anonymous-first, with claim via Apple Sign-In or
email magic-link.

These mirror Supabase Auth shapes closely enough that the swap-over
is mostly mechanical: drop our `users` + `auth_challenges` tables and
point the same endpoints at supabase-py.

Flow:

  1. Splash → POST /v1/auth/anon  (device_user_id from shared_preferences)
     → Backend creates a `users` row with is_anonymous=True and returns
       a session token that mobile stores. user_id == device_user_id.

  2. Onboarding → mandate is keyed by user_id. The same id survives claim.

  3. Settings → "Sign in"
     → POST /v1/auth/magic_link/start { email }
        Backend stashes a hashed 6-digit code in auth_challenges,
        returns 200 (in dev the code is also returned in the body for
        copy-paste convenience).
     → POST /v1/auth/magic_link/verify { email, code, user_id }
        Backend verifies, marks the user row claimed (email = ...),
        bumps claimed_at.

  OR
     → POST /v1/auth/apple { identity_token, user_id }
        Decodes the Apple JWT *unverified* in scaffold mode (just reads
        the `sub` claim). Marks the user row claimed with apple_id=sub.
        Real prod plugs in apple_id_jwt verification + Supabase ID-token
        exchange.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AuthUser(BaseModel):
    id: UUID
    email: str | None = None
    apple_id: str | None = None
    is_anonymous: bool
    claimed_at: datetime | None = None
    created_at: datetime


class AnonSessionRequest(BaseModel):
    device_user_id: UUID | None = Field(
        default=None,
        description="Stable UUID generated by the mobile client. If missing, "
                    "the backend generates one and returns it.",
    )
    locale: str = "en"
    timezone: str = "UTC"


class AnonSessionResponse(BaseModel):
    user: AuthUser
    token: str
    is_new: bool


class MagicLinkStartRequest(BaseModel):
    email: str
    # Note: previously accepted `user_id` from the body. Removed by the
    # adversarial audit (2026-05-18) finding A3 — the claim is bound to
    # the caller's Bearer token instead.


class MagicLinkStartResponse(BaseModel):
    sent: bool
    debug_code: str | None = None  # only populated when env=local


class MagicLinkVerifyRequest(BaseModel):
    email: str
    code: str
    # Note: `user_id` removed — see MagicLinkStartRequest comment.


class AppleSignInRequest(BaseModel):
    """Identity-token exchange.

    Scaffold mode (no Supabase): decode the JWT body without signature
    verification and treat the `sub` as the user's stable apple_id. This
    is NOT secure — production swap-in does proper key-rotation + JWKS
    validation, OR delegates to Supabase Auth which does it for us.
    """

    identity_token: str
    user_id: UUID | None = None
    full_name: str | None = None


class AuthVerifyResponse(BaseModel):
    user: AuthUser
    token: str
    claimed: bool


class SessionToken(BaseModel):
    """Opaque session token — currently just `user_id` hex; when Supabase
    plugs in, this becomes their access JWT."""

    token: str
    user_id: UUID
    kind: Literal["scaffold", "supabase"] = "scaffold"
