"""Auth schemas — anonymous-first, with claim via Apple Sign-In or
email magic-link.

These mirror Supabase Auth shapes closely enough that the swap-over
is mostly mechanical: drop our `users` + `auth_challenges` tables and
point the same endpoints at supabase-py.

Flow:

  1. Splash → POST /v1/auth/anon  (device_user_id from shared_preferences)
     → Backend creates a `users` row with is_anonymous=True and returns
       a session token that mobile stores. user_id == device_user_id.

  2. Onboarding → mandate is keyed by user_id. The same id survives claim.

  3. Settings → "Sign in"
     → POST /v1/auth/magic_link/start { email }
        Backend stashes a hashed 6-digit code in auth_challenges,
        returns 200 (in dev the code is also returned in the body for
        copy-paste convenience).
     → POST /v1/auth/magic_link/verify { email, code, user_id }
        Backend verifies, marks the user row claimed (email = ...),
        bumps claimed_at.

  OR
     → POST /v1/auth/apple { identity_token, user_id }
        Decodes the Apple JWT *unverified* in scaffold mode (just reads
        the `sub` claim). Marks the user row claimed with apple_id=sub.
        Real prod plugs in apple_id_jwt verification + Supabase ID-token
        exchange.
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AuthUser(BaseModel):
    id: UUID
    email: str | None = None
    apple_id: str | None = None
    google_id: str | None = None
    display_name: str | None = None
    is_anonymous: bool
    claimed_at: datetime | None = None
    created_at: datetime


class AnonSessionRequest(BaseModel):
    device_user_id: UUID | None = Field(
        default=None,
        description="Stable UUID generated by the mobile client. If missing, "
                    "the backend generates one and returns it.",
    )
    locale: str = "en"
    timezone: str = "UTC"
    # BL1 (AT:R33): mobile sends device + build context for admin support
    # context. All optional — old clients still bootstrap fine.
    device_model: str | None = Field(default=None, max_length=128)
    os_version: str | None = Field(default=None, max_length=64)
    app_version: str | None = Field(default=None, max_length=64)
    # BL2 (AT:R33): stable per-install identifier. Generated once on first
    # launch in shared_prefs and never overwritten (unlike device_user_id,
    # which mobile overwrites with the adopted user_id on claim). Keys the
    # user_devices table so the same human's two phones don't collapse into
    # one device row after Apple/email claim merge.
    device_install_id: UUID | None = None


class AnonSessionResponse(BaseModel):
    user: AuthUser
    token: str
    is_new: bool


class MagicLinkStartRequest(BaseModel):
    email: str
    # Note: previously accepted `user_id` from the body. Removed by the
    # adversarial audit (2026-05-18) finding A3 — the claim is bound to
    # the caller's Bearer token instead.


class MagicLinkStartResponse(BaseModel):
    sent: bool
    debug_code: str | None = None  # only populated when env=local


class MagicLinkVerifyRequest(BaseModel):
    email: str
    code: str
    # Note: `user_id` removed — see MagicLinkStartRequest comment.
    # BL13 (AT:R32): optional binding of the OnboardingSession that produced
    # this user. Backwards-compatible — old clients omit it and the binding
    # silently skips. Server-side use: cohort analysis (claim rate per
    # Concierge variant) + GDPR deletion + onboarding replay.
    onboarding_session_id: UUID | None = None


class AppleSignInRequest(BaseModel):
    """Identity-token exchange.

    Scaffold mode (no Supabase): decode the JWT body without signature
    verification and treat the `sub` as the user's stable apple_id. This
    is NOT secure — production swap-in does proper key-rotation + JWKS
    validation, OR delegates to Supabase Auth which does it for us.
    """

    identity_token: str
    user_id: UUID | None = None
    full_name: str | None = None
    # BL13 (AT:R32): see MagicLinkVerifyRequest.onboarding_session_id.
    onboarding_session_id: UUID | None = None


class GoogleSignInRequest(BaseModel):
    """Google Sign-In identity-token exchange (Android only at alpha).

    Mirrors AppleSignInRequest. Unlike Apple, Google ships `email` +
    `name` in EVERY ID token (not first-only), so the client doesn't
    need a separate `full_name` field — the backend pulls it from
    verified claims. Per D-057 minimum-data policy, only `sub`, `email`,
    `name` are persisted; other claims (`picture`, `locale`, `given_name`,
    `family_name`, `hd`) are dropped.
    """

    identity_token: str
    user_id: UUID | None = None
    onboarding_session_id: UUID | None = None


class AuthVerifyResponse(BaseModel):
    user: AuthUser
    token: str
    claimed: bool
    # BL16 (AT:R38): when an email-fallback adoption fires (caller's anon
    # user_id != the row returned by email/sub lookup), this carries the
    # pre-claim anon's user_id so the client can offer a merge UX. None on
    # the common case where the same row was promoted in place.
    adopted_from_user_id: UUID | None = None


class MergeAccountRequest(BaseModel):
    """Body for POST /v1/auth/merge — the adopting user merges data from a
    pre-claim anon orphan that was left behind during account-linking
    Phase 1 (AT:R32). Caller's Bearer must be the adopting user."""

    from_user_id: UUID


class MergePreview(BaseModel):
    """Read-only counts of what an account merge would move from the orphan
    `from_user_id` into the adopting `to_user_id`. Mandate is special-cased
    because both rows may carry one — we always keep the adopting user's."""

    from_user_id: UUID
    to_user_id: UUID
    journal_entries: int = 0
    sim_trades: int = 0
    sim_holdings: int = 0
    sim_watchlists: int = 0
    lessons_progress: int = 0
    agent_activations: int = 0
    one_on_one_messages: int = 0
    room_runs: int = 0
    user_overlays: int = 0
    bug_reports: int = 0
    mandate_conflict: bool = False


class MergeResult(BaseModel):
    """Outcome of POST /v1/auth/merge. `counts` is per-category rows moved
    into the adopting user. `mandate_kept` says which side won when both
    had a mandate. `overlays_deactivated` counts source overlays that were
    re-keyed but marked inactive because the target already had an active
    overlay for the same agent."""

    from_user_id: UUID
    to_user_id: UUID
    counts: Dict[str, int]
    mandate_kept: Literal["target", "source", "neither"]
    overlays_deactivated: int = 0


class SessionToken(BaseModel):
    """Opaque session token — currently just `user_id` hex; when Supabase
    plugs in, this becomes their access JWT."""

    token: str
    user_id: UUID
    kind: Literal["scaffold", "supabase"] = "scaffold"
