"""Promote crawl findings into the dispatch pipeline (CR163).

    python3 tools/triage.py <run-dir> [--file <fingerprint> ...] [--reject <fp> ...]

This is a **separate step from the crawl on purpose**. CR080 lost two sessions
to a harness bug being written up as 27 application failures, and the standing
rule since then is that the harness never files a defect itself. An autonomous
crawler makes that rule more important, not less: one bad build, one wedged
simulator, one oracle regression, and an auto-filing crawler floods the register
with fiction that a fixer agent then dutifully "fixes".

So the gate stays, but it is cheap: triage reads the run, shows each new
finding with its evidence, and writes an **intake stub** for the ones accepted.

**Why an intake stub and not a DEF row.** `DEF###` ids are minted by one owner
so two tracks cannot collide on a number (CLAUDE.md, "the Architect is the
single ID-minter"). A script minting ids autonomously is exactly the race that
rule exists to prevent. The stub path is the project's existing pre-triage
lane — topic-slug handle now, number when it is picked up — and it is a disjoint
write path per finding, so concurrent triage runs cannot sweep each other.

Handoff to the fixer agent is then the normal one: stub -> Architect mints
`DEF###` + writes the assign lane -> `coder.*` fixes -> auditor verdict
(`orchestration/dispatch/DISPATCH_PROTOCOL.md`).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from crawler.ledger import FALSE_POSITIVE, FILED, Ledger, fingerprint  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
INTAKE_DIR = REPO_ROOT / "orchestration" / "dispatch" / "intake"


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60] or "finding"


def _stub(finding: dict, fp: str, run_dir: Path) -> str:
    rule = finding.get("check") or finding.get("rule") or "unknown"
    return f"""<!-- intake stub — AUTOGENERATED by qa/appium/tools/triage.py (CR163) from an
     autonomous crawl, then ACCEPTED by a human/Architect review. Architect triages + mints. -->
# crawl-{_slug(rule)}-{fp[:8]} — proposed DEF: {rule} on screen {finding.get('screen', 'n/a')}

PROPOSED-KIND: DEF
SOURCE: autonomous crawler (CR163), run `{run_dir.name}`
TRIAGE: ACCEPTED-BY-REVIEW
FINGERPRINT: {fp}
SEVERITY: {finding.get('severity', 'unknown')}

**What the crawler saw:** {finding.get('note', '(no note)')}

- rule: `{rule}`
- screen fingerprint: `{finding.get('screen', 'n/a')}`
- detail: {finding.get('detail') or finding.get('element_label') or '—'}
- occurrences during the crawl: {finding.get('count', 1)}

**Evidence** (run directory `{run_dir}`):

- `report.md` — the crawl path that reached this screen
- `findings.json` — this finding verbatim
- the app's own error record, read from its container at the end of the run
  (`mobile/lib/qa/error_sink.dart`)
- screenshot: `{finding.get('screenshot', '(none captured)')}`

```
{(finding.get('sample') or '')[:400]}
```

**Before fixing, confirm it reproduces.** A crawler finding is a *lead*, not a
verified defect: it was produced by machinery that has been wrong before
(CR080's 27 false failures came from one harness `TypeError`). Reproduce it by
hand or with a targeted test first, and if it does not reproduce, mark the
fingerprint `false_positive` in `qa/appium/crawler/known_findings.json` rather
than deleting this stub silently — the ledger is what stops it being
rediscovered every night.
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Triage a crawl run into the dispatch pipeline")
    parser.add_argument("run_dir", type=Path)
    parser.add_argument("--file", nargs="*", default=[], metavar="FP",
                        help="fingerprints to promote to an intake stub")
    parser.add_argument("--reject", nargs="*", default=[], metavar="FP",
                        help="fingerprints to mark false_positive (never reported again)")
    parser.add_argument("--list", action="store_true", help="show findings + fingerprints and exit")
    args = parser.parse_args(argv[1:])

    payload = json.loads((args.run_dir / "findings.json").read_text())
    findings = payload["new"]
    by_fp = {fingerprint(f): f for f in findings}

    if args.list or (not args.file and not args.reject):
        print(f"{len(findings)} new finding(s) in {args.run_dir}\n")
        for fp, f in by_fp.items():
            print(f"  {fp}  [{f.get('severity','?'):6}] {f.get('check') or f.get('rule')}"
                  f"  screen={f.get('screen','n/a')}  {(f.get('detail') or '')[:40]}")
        print("\nPromote:  tools/triage.py <run-dir> --file <fp> [<fp> ...]"
              "\nReject :  tools/triage.py <run-dir> --reject <fp> [<fp> ...]")
        return 0

    ledger = Ledger()
    INTAKE_DIR.mkdir(parents=True, exist_ok=True)

    for fp in args.file:
        finding = by_fp.get(fp)
        if finding is None:
            print(f"!! {fp} is not a finding in this run", file=sys.stderr)
            return 1
        rule = finding.get("check") or finding.get("rule") or "unknown"
        path = INTAKE_DIR / f"crawl-{_slug(rule)}-{fp[:8]}.md"
        path.write_text(_stub(finding, fp, args.run_dir))
        ledger.record(finding, status=FILED, note=f"intake stub {path.name}")
        print(f"filed  {fp} -> {path.relative_to(REPO_ROOT)}")

    for fp in args.reject:
        finding = by_fp.get(fp)
        if finding is None:
            print(f"!! {fp} is not a finding in this run", file=sys.stderr)
            return 1
        ledger.record(finding, status=FALSE_POSITIVE, note="rejected at triage")
        print(f"reject {fp} -> will not be reported again")

    ledger.save()
    print("\nledger updated. Next: the Architect mints DEF### for each stub and writes the "
          "assign lane (orchestration/dispatch/DISPATCH_PROTOCOL.md); coder.* fixes; "
          "auditor issues the verdict.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
